//**************************************************************
//
//  Errors
//
//  Created by Harish Kataria
//  Copyright © 2018 Harish Kataria. All rights reserved.
//
//**************************************************************

import Foundation

/**
 * Alias for Any type
 */
public typealias Kind = Any.Type

/**
 * Custom errors generated by the framework
 */
public enum EcosystemError: Error {
    /**
     * A entity, of the given kind, was not found
     */
    case notFound(Kind)
    /**
     * A entity, of the given kind, was not matched
     */
    case mismatch(Any, Kind)
    /**
     * A entity, of the given kind, has circular dependencies
     */
    case circularDependency(Kind)
    /**
     * new entities demand conflicted with the population limit
     */
    case incompatibleWithPopulationThreshold(ofKind: Kind)
}
